hydra:
  job:
    chdir: false
registry: inr_0909
run_dir: null
dataset:
  name: PJM
  batch_size: 64
  missing_rate: 0.0
seed: 42
device: auto
model_uid: null
model:
  name: inr
  num_epoch: 100
  lookback: 168
  horizon: 24
  optim:
    lr: 0.001
    lr_inr: 0.0004
    lr_pe: 0.0002
  deepsets:
    input_dim: 2
    hidden_dim: 64
  lstm:
    input_dim: 2
    hidden_dim: 96
  inr:
    num_frequencies: 32
    pe_learnable: true
    hidden_dim: 64
    activation: gelu
    num_layers: 1
    output_dim: 1
    film_hidden_dim: 64
mlflow:
  experiment_name: icassp-veridis
  run_name: null