hydra:
  job:
    chdir: false

registry: ???
run_dir: null

dataset:
  name: FR
  batch_size: 64
  missing_rate: 0.0

seed: 42
device: auto

model_uid: null

model:
  name: "inr"
  lr: 0.001
  num_epoch: 50
  grad_clip_norm: 1.0
  lookback: 144
  horizon: 24

  deepsets:
    input_dim: 2
    hidden_dim: 64
    aggregation: sum

  lstm:
    input_dim: 2
    hidden_dim: 256

  inr:
    num_frequencies: 8
    hidden_dim: 64
    num_layers: 3
    output_dim: 1
    film_hidden_dim: 128

mlflow:
  experiment_name: icassp-1-tokill
  run_name: null


