hydra:
  job:
    chdir: false

registry: ???
run_dir : null

dataset:
  name: NP #FR et autres
  batch_size: 32
  missing_rate: 0.1

seed: 42
device: auto

model_uid: null

model:
  test: "ok"
  lr: 0.001


mlflow:
  experiment_name: optuna_test
  run_name: null